cameras:
- id: camera_01
  name: Front Entrance Entry
  url: rtsp://admin:admin123@175.29.168.110:6222/cam/realmonitor?channel=31&subtype=0
  active: true
  roi: [64, 528, 1241, 1079]
- id: camera_02
  name: Front Entrance Exit
  url: rtsp://admin:admin123@175.29.168.110:6222/cam/realmonitor?channel=25&subtype=0
  active: true
  roi: [538, 219, 1818, 1050]
