# Camera configuration
cameras:
  - id: camera_01
    url: C:/Users/acer/Desktop/TDI/Ha-meem/test_videos/albid.mp4
    name: Front Entrance
  - id: camera_02
    url: C:/Users/acer/Desktop/TDI/Ha-meem/test_videos/ismum.mp4
    name: Back Exit
